### ISSUE TITLE
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.

### ISSUE THREAD

**Issue by travisboss** [imagegenius/docker-immich-cuda-node#12]
```
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
```

See this pop up at the end of the container, is this an issue?

```yaml
  immich-cuda-node:
    image: ghcr.io/imagegenius/immich-cuda-node:latest
    runtime: nvidia
    container_name: immich-cuda-node
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /pool/datavault/immich/cuda/config:/var/lib/postgresql/data
      - /pool/datavault/immich/photos:/photos
    ports:
      - 3003:3003
    restart: unless-stopped
    networks:
      - docker-services
    security_opt:
      - no-new-privileges=true
```

Here is what the compose file looks like, thanks.

**Comment by hydazz** [comment]
not sure you can you can use `runtime` in docker compose, might be wrong, but 
```yaml
version: "3"

services:
  immich-cuda-node:
    image: ghcr.io/imagegenius/immich-cuda-node:latest
    container_name: immich-cuda-node
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /pool/datavault/immich/cuda/config:/var/lib/postgresql/data
      - /pool/datavault/immich/photos:/photos
    ports:
      - 3003:3003
    restart: unless-stopped
    networks:
      - docker-services
    security_opt:
      - no-new-privileges=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
``` 
is whats needed to passthrough a GPU via compose

`Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.`

don't believe this means anythings wrong, @martabal?
